require("core.keymaps")
require("core.set")
require("core.plugins")
require("core.plugin_config")
vim.api.nvim_set_keymap("n", "<M-Left>", "<C-w>h", { silent = true })
vim.api.nvim_set_keymap("n", "<M-Right>", "<C-w>l", { silent = true })
vim.api.nvim_set_keymap("n", "<M-Down>", "<C-w>j", { silent = true })
vim.api.nvim_set_keymap("n", "<M-Up>", "<C-w>k", { silent = true })
